# Form implementation generated from reading ui file 'master_window.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(487, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("/*\n"
"Material Dark Style Sheet for QT Applications\n"
"Author: Jaime A. Quiroga P.\n"
"Inspired on https://github.com/jxfwinter/qt-material-stylesheet\n"
"Company: GTRONICK\n"
"Last updated: 04/12/2018, 15:00.\n"
"Available at: https://github.com/GTRONICK/QSS/blob/master/MaterialDark.qss\n"
"*/\n"
"QMainWindow {\n"
"    background-color:#1e1d23;\n"
"}\n"
"QDialog {\n"
"    background-color:#1e1d23;\n"
"}\n"
"QColorDialog {\n"
"    background-color:#1e1d23;\n"
"}\n"
"QTextEdit {\n"
"    background-color:#1e1d23;\n"
"    color: #a9b7c6;\n"
"}\n"
"QToolButton {\n"
"    border-style: solid;\n"
"    border-radius: 20px;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #04b97f;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QPushButton{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: #c0c0c0;\n"
"}\n"
"QPushButton::default{\n"
"    border-style: inset;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #04b97f;\n"
"    border-width: 1px;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #FFFFFF;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #FFFFFF;\n"
"    padding-bottom: 2px;\n"
"    background-color: #ffd700;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #FFFFFF;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #FFFFFF;\n"
"    padding-bottom: 1px;\n"
"    background-color: #e6c619;\n"
"}\n"
"QPushButton:disabled{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #808086;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #808086;\n"
"    padding-bottom: 1px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #37efba;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #FFFFFF;\n"
"    padding-bottom: 1px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QLineEdit {\n"
"    border-width: 1px; border-radius: 4px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    padding: 0 8px;\n"
"    color: #a9b7c6;\n"
"    background:#1e1d23;\n"
"    selection-background-color:#007b50;\n"
"    selection-color: #FFFFFF;\n"
"}\n"
"QLabel {\n"
"    color: #a9b7c6;\n"
"}\n"
"QLCDNumber {\n"
"    color: #37e6b4;\n"
"}\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(240, 240, 240);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    background-color:#1e1d23;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #ffd700;\n"
"    border-radius: 5px;\n"
"}\n"
"QMenuBar {\n"
"    background-color: #1e1d23;\n"
"}\n"
"QMenuBar::item {\n"
"    color: #a9b7c6;\n"
"      spacing: 3px;\n"
"      padding: 1px 4px;\n"
"      background: #1e1d23;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"      background:#1e1d23;\n"
"    color: #ffd700;\n"
"}\n"
"QMenu::item:selected {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: #ffd700;\n"
"    border-bottom-color: transparent;\n"
"    border-left-width: 2px;\n"
"    color: #FFFFFF;\n"
"    padding-left:15px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QMenu::item {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #a9b7c6;\n"
"    padding-left:17px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QMenu{\n"
"    background-color:#1e1d23;\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:#1e1d23;\n"
"}\n"
"QTabWidget::pane {\n"
"        border-color: rgb(77,77,77);\n"
"        background-color:#1e1d23;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-radius: 6px;\n"
"}\n"
"QTabBar::tab {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #808086;\n"
"    padding: 3px;\n"
"    margin-left:3px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"      border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #04b97f;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #FFFFFF;\n"
"    padding-left: 3px;\n"
"    padding-bottom: 2px;\n"
"    margin-left:3px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"}\n"
"QCheckBox:disabled {\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-width:1px;\n"
"    border-color: rgb(87, 97, 106);\n"
"    background-color:#1e1d23;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #04b97f;\n"
"    color: #a9b7c6;\n"
"    background-color: #04b97f;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #04b97f;\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QRadioButton {\n"
"    color: #a9b7c6;\n"
"    background-color: #1e1d23;\n"
"    padding: 1px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: #04b97f;\n"
"    color: #a9b7c6;\n"
"    background-color: #04b97f;\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: #04b97f;\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QStatusBar {\n"
"    color:#027f7f;\n"
"}\n"
"QSpinBox {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QDoubleSpinBox {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QTimeEdit {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QDateTimeEdit {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QDateEdit {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QComboBox {\n"
"    color: #a9b7c6;    \n"
"    background: #1e1d23;\n"
"}\n"
"QComboBox:editable {\n"
"    background: #1e1d23;\n"
"    color: #a9b7c6;\n"
"    selection-background-color: #1e1d23;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: #a9b7c6;    \n"
"    background: #1e1d23;\n"
"    selection-color: #FFFFFF;\n"
"    selection-background-color: #1e1d23;\n"
"}\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    color: #a9b7c6;    \n"
"    background: #1e1d23;\n"
"}\n"
"QFontComboBox {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolBox {\n"
"    color: #a9b7c6;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolBox::tab {\n"
"    color: #a9b7c6;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolBox::tab:selected {\n"
"    color: #FFFFFF;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QScrollArea {\n"
"    color: #FFFFFF;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background: #04b97f;\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 5px;\n"
"    background: #04b97f;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 14px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: qlineargradient(x1:1, y1:1, x2:0, y2:0, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    height: 14px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: white;\n"
"}\n"
"QSlider::add-page:vertical {\n"
"    background: white;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background: #04b97f;\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"    background: #04b97f;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-10, -30, 501, 571))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setBold(False)
        font.setStrikeOut(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QtabWidget\n"
"\n"
"{\n"
"    background-color: #c0c0c0\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.welcome_fr = QtWidgets.QWidget()
        self.welcome_fr.setObjectName("welcome_fr")
        self.welcom_split_line = QtWidgets.QFrame(parent=self.welcome_fr)
        self.welcom_split_line.setGeometry(QtCore.QRect(10, 118, 481, 20))
        self.welcom_split_line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.welcom_split_line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.welcom_split_line.setObjectName("welcom_split_line")
        self.do_work_with_video_pb = QtWidgets.QFrame(parent=self.welcome_fr)
        self.do_work_with_video_pb.setGeometry(QtCore.QRect(10, 70, 181, 51))
        self.do_work_with_video_pb.setStyleSheet("")
        self.do_work_with_video_pb.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.do_work_with_video_pb.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.do_work_with_video_pb.setObjectName("do_work_with_video_pb")
        self.create_form_for_video_pb = QtWidgets.QPushButton(parent=self.do_work_with_video_pb)
        self.create_form_for_video_pb.setGeometry(QtCore.QRect(20, 0, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        self.create_form_for_video_pb.setFont(font)
        self.create_form_for_video_pb.setStyleSheet("QPushButton {\n"
"    color: #141619\n"
"}\n"
"")
        self.create_form_for_video_pb.setAutoRepeatDelay(300)
        self.create_form_for_video_pb.setObjectName("create_form_for_video_pb")
        self.play_pb = QtWidgets.QPushButton(parent=self.do_work_with_video_pb)
        self.play_pb.setGeometry(QtCore.QRect(130, 0, 41, 41))
        self.play_pb.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: #1f883d;\n"
"    color: #E1E1E1\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #24B34F;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #FFFFFF;\n"
"    padding-bottom: 2px;\n"
"    background-color: #24B34F;\n"
"}")
        self.play_pb.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Qt/qt files for project/play(1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.play_pb.setIcon(icon)
        self.play_pb.setIconSize(QtCore.QSize(38, 38))
        self.play_pb.setCheckable(False)
        self.play_pb.setObjectName("play_pb")
        self.video_process_fr = QtWidgets.QFrame(parent=self.welcome_fr)
        self.video_process_fr.setGeometry(QtCore.QRect(30, 120, 441, 401))
        self.video_process_fr.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.video_process_fr.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.video_process_fr.setObjectName("video_process_fr")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.video_process_fr)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 441, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.video_process_vl = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.video_process_vl.setContentsMargins(0, 0, 0, 0)
        self.video_process_vl.setObjectName("video_process_vl")
        self.ideal_video_process_fr = QtWidgets.QFrame(parent=self.verticalLayoutWidget)
        self.ideal_video_process_fr.setStyleSheet("")
        self.ideal_video_process_fr.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ideal_video_process_fr.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ideal_video_process_fr.setObjectName("ideal_video_process_fr")
        self.label = QtWidgets.QLabel(parent=self.ideal_video_process_fr)
        self.label.setGeometry(QtCore.QRect(106, 10, 61, 47))
        self.label.setStyleSheet("QLabel {\n"
"    border: 2px solid #c0c0c0;\n"
"}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Qt/qt files for project/aaa.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.border_procecc_l = QtWidgets.QLabel(parent=self.ideal_video_process_fr)
        self.border_procecc_l.setGeometry(QtCore.QRect(-12, 5, 451, 61))
        self.border_procecc_l.setText("")
        self.border_procecc_l.setPixmap(QtGui.QPixmap("../../Qt/qt files for project/border.png"))
        self.border_procecc_l.setScaledContents(True)
        self.border_procecc_l.setObjectName("border_procecc_l")
        self.progressBar = QtWidgets.QProgressBar(parent=self.ideal_video_process_fr)
        self.progressBar.setGeometry(QtCore.QRect(174, 10, 251, 22))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.whats_happen_now_l = QtWidgets.QLabel(parent=self.ideal_video_process_fr)
        self.whats_happen_now_l.setGeometry(QtCore.QRect(176, 40, 251, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(11)
        self.whats_happen_now_l.setFont(font)
        self.whats_happen_now_l.setStyleSheet("QLabel{\n"
"    padding-left: center;\n"
"}")
        self.whats_happen_now_l.setObjectName("whats_happen_now_l")
        self.settings_pb = QtWidgets.QPushButton(parent=self.ideal_video_process_fr)
        self.settings_pb.setGeometry(QtCore.QRect(12, 16, 41, 41))
        self.settings_pb.setStyleSheet("")
        self.settings_pb.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Qt/qt files for project/settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.settings_pb.setIcon(icon1)
        self.settings_pb.setIconSize(QtCore.QSize(28, 28))
        self.settings_pb.setObjectName("settings_pb")
        self.delete_pb = QtWidgets.QPushButton(parent=self.ideal_video_process_fr)
        self.delete_pb.setGeometry(QtCore.QRect(60, 16, 41, 41))
        self.delete_pb.setStyleSheet("QPushButton{\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: #ff618a;\n"
"}\n"
"QPushButton::default{\n"
"    border-style: inset;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: black;\n"
"    border-width: 1px;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: #ff618a;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: black;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: black;\n"
"    padding-bottom: 2px;\n"
"    background-color: #cd3059;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: black;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #37efba;\n"
"    padding-bottom: 1px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QPushButton:disabled{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #808086;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #808086;\n"
"    padding-bottom: 1px;\n"
"    background-color: #1e1d23;\n"
"}")
        self.delete_pb.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Qt/qt files for project/del.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.delete_pb.setIcon(icon2)
        self.delete_pb.setIconSize(QtCore.QSize(28, 28))
        self.delete_pb.setObjectName("delete_pb")
        self.radioButton = QtWidgets.QRadioButton(parent=self.ideal_video_process_fr)
        self.radioButton.setGeometry(QtCore.QRect(410, 40, 16, 20))
        self.radioButton.setText("")
        self.radioButton.setObjectName("radioButton")
        self.border_procecc_l.raise_()
        self.label.raise_()
        self.progressBar.raise_()
        self.whats_happen_now_l.raise_()
        self.settings_pb.raise_()
        self.delete_pb.raise_()
        self.radioButton.raise_()
        self.video_process_vl.addWidget(self.ideal_video_process_fr)
        self.tabWidget.addTab(self.welcome_fr, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 487, 19))
        self.menuBar.setObjectName("menuBar")
        self.menusettings = QtWidgets.QMenu(parent=self.menuBar)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        self.menusettings.setFont(font)
        self.menusettings.setObjectName("menusettings")
        self.menubalance = QtWidgets.QMenu(parent=self.menuBar)
        self.menubalance.setObjectName("menubalance")
        self.menuReference = QtWidgets.QMenu(parent=self.menuBar)
        self.menuReference.setObjectName("menuReference")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAdd_preference = QtGui.QAction(parent=MainWindow)
        self.actionAdd_preference.setObjectName("actionAdd_preference")
        self.actionshow_balance = QtGui.QAction(parent=MainWindow)
        self.actionshow_balance.setObjectName("actionshow_balance")
        self.action_hange_directory = QtGui.QAction(parent=MainWindow)
        self.action_hange_directory.setObjectName("action_hange_directory")
        self.actionGlobal_settings = QtGui.QAction(parent=MainWindow)
        self.actionGlobal_settings.setObjectName("actionGlobal_settings")
        self.menusettings.addAction(self.actionAdd_preference)
        self.menusettings.addAction(self.action_hange_directory)
        self.menusettings.addSeparator()
        self.menusettings.addAction(self.actionGlobal_settings)
        self.menubalance.addAction(self.actionshow_balance)
        self.menuBar.addAction(self.menusettings.menuAction())
        self.menuBar.addAction(self.menubalance.menuAction())
        self.menuBar.addAction(self.menuReference.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.create_form_for_video_pb.setText(_translate("MainWindow", "video"))
        self.whats_happen_now_l.setText(_translate("MainWindow", "What\'s happen now! (76/233) "))
        self.radioButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>{Name video}</p></body></html>"))
        self.radioButton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>AAAAA</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.welcome_fr), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menusettings.setTitle(_translate("MainWindow", "settings"))
        self.menubalance.setTitle(_translate("MainWindow", "balance"))
        self.menuReference.setTitle(_translate("MainWindow", "Reference"))
        self.actionAdd_preference.setText(_translate("MainWindow", "Add preference"))
        self.actionshow_balance.setText(_translate("MainWindow", "show balance"))
        self.action_hange_directory.setText(_translate("MainWindow", "Сhange directory"))
        self.actionGlobal_settings.setText(_translate("MainWindow", "Global settings"))
